"""Shared semantic data and interfaces for Typeforge adapters."""

from typeforge.semantics.errors import SemanticIssue, SemanticIssueCode
from typeforge.semantics.evaluation import evaluate
from typeforge.semantics.model import (
    AllExpression,
    AnyExpression,
    AssignableExpression,
    CaseExpression,
    DropExpression,
    DroppedField,
    EqualExpression,
    EvaluationContext,
    EvaluationValue,
    Expression,
    FieldExpression,
    FieldName,
    InputReference,
    KeyReference,
    MapExpression,
    MapFieldsExpression,
    NotExpression,
    OptionalFieldExpression,
    ReadonlyFieldExpression,
    RecordFamily,
    RecordField,
    RecordShape,
    ResolvedType,
    TypeReference,
    UnionExpression,
    ValueReference,
    type_ref,
)
from typeforge.semantics.protocols import TypeSystem

__all__ = (
    "AllExpression",
    "AnyExpression",
    "AssignableExpression",
    "CaseExpression",
    "DropExpression",
    "DroppedField",
    "EqualExpression",
    "EvaluationContext",
    "EvaluationValue",
    "Expression",
    "FieldExpression",
    "FieldName",
    "InputReference",
    "KeyReference",
    "MapExpression",
    "MapFieldsExpression",
    "NotExpression",
    "OptionalFieldExpression",
    "ReadonlyFieldExpression",
    "RecordFamily",
    "RecordField",
    "RecordShape",
    "ResolvedType",
    "SemanticIssue",
    "SemanticIssueCode",
    "TypeReference",
    "TypeSystem",
    "UnionExpression",
    "ValueReference",
    "evaluate",
    "type_ref",
)
